"""add status to frecord

Revision ID: 7ac1b0d583e3
Revises: c7340944b0b7
Create Date: 2026-04-04 10:03:10.635585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac1b0d583e3'
down_revision = 'c7340944b0b7'
branch_labels = None
depends_on = None


def upgrade():
    my_enum = sa.Enum('active', 'inactive', name='financial_record_status')
    my_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', my_enum, server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_column('status')
    my_enum = sa.Enum('active', 'inactive', name='financial_record_status')
    my_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
